// resources/js/vue/Pages/Auth/VerifyEmail.vue
<template>
  <div class="mb-4 text-sm text-gray-600">
    Thanks for signing up! Before getting started, could you verify your email
    address by clicking on the link we just emailed to you? If you didn't
    receive the email, we will gladly send you another.
  </div>

  <div
    class="mb-4 font-medium text-sm text-green-600"
    v-if="verificationLinkSent"
  >
    A new verification link has been sent to the email address you provided
    during registration.
  </div>

  <form @submit.prevent="submit">
    <div class="mt-4 flex items-center justify-between">
      <breeze-button
        :class="{ 'opacity-25': form.processing }"
        :disabled="form.processing"
      >
        Resend Verification Email
      </breeze-button>

      <inertia-link
        :href="route('vue.logout')"
        method="post"
        as="button"
        class="underline text-sm text-gray-600 hover:text-gray-900"
        >Log Out</inertia-link
      >
    </div>
  </form>
</template>

<script>
import BreezeButton from "../../Components/Button";
import BreezeGuestLayout from "../../Layouts/Guest";

export default {
  layout: BreezeGuestLayout,

  components: {
    BreezeButton,
  },

  props: {
    status: String,
  },

  data() {
    return {
      form: this.$inertia.form(),
    };
  },

  methods: {
    submit() {
      this.form.post(this.route("vue.verification.send"));
    },
  },

  computed: {
    verificationLinkSent() {
      return this.status === "verification-link-sent";
    },
  },
};
</script>

// resources/js/react/Pages/Auth/VerifyEmail.jsx
import React from "react";
import { InertiaLink } from "@inertiajs/inertia-react";
import { useForm } from "@inertiajs/inertia-react";
import Button from "../../Components/Button";
import Guest from "../../Layouts/Guest";

export default function VerifyEmail({ status }) {
  const { post, processing } = useForm();

  const submit = (e) => {
    e.preventDefault();

    post(route("react.verification.send"));
  };

  return (
    <Guest>
      <div className="mb-4 text-sm text-gray-600">
        Thanks for signing up! Before getting started, could you verify your
        email address by clicking on the link we just emailed to you? If you
        didn't receive the email, we will gladly send you another.
      </div>

      {status === "verification-link-sent" && (
        <div className="mb-4 font-medium text-sm text-green-600">
          A new verification link has been sent to the email address you
          provided during registration.
        </div>
      )}

      <form onSubmit={submit}>
        <div className="mt-4 flex items-center justify-between">
          <Button processing={processing}>Resend Verification Email</Button>

          <InertiaLink
            href={route("logout")}
            method="post"
            as="button"
            className="underline text-sm text-gray-600 hover:text-gray-900"
          >
            Log Out
          </InertiaLink>
        </div>
      </form>
    </Guest>
  );
}
